/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp_id;

import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.saxon.s9api.SaxonApiException;
import org.jdom2.Document;
import static tp_id.TP_ID.adicionaInfoAmbosFicheiros;
import static tp_id.TP_ID.alteraCidadePopulosa;
import static tp_id.TP_ID.alteraPopulacao;
import static tp_id.TP_ID.alteraPresidente;
import static tp_id.TP_ID.procura_pais_por_continente;
import static tp_id.TP_ID.procura_pais_por_idioma;
import static tp_id.TP_ID.removePaisFicheiros;
import static tp_id.TP_ID.validarDocumentoDTD;
import static tp_id.TP_ID.validarDocumentoXSD;

/**
 *
 * @author joaop
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JanelaAdicionaPais = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        CampoTextPaisParaAdicionar = new javax.swing.JTextField();
        BotaoAdicionarPais = new javax.swing.JButton();
        JanelaRemovePais = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        CampoTextPaisParaRemover = new javax.swing.JTextField();
        BotaoRemoverPais = new javax.swing.JButton();
        JanelaEditaPresi = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        CampoTextPaisParaEditarPres = new javax.swing.JTextField();
        BotaoEditaPresi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CampoTextPresidente = new javax.swing.JTextField();
        JanelaEditaPop = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        CampoTextPaisParaEditarPop = new javax.swing.JTextField();
        BotaoEditaPop = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CampoTextPopulacao = new javax.swing.JTextField();
        JanelaEditaCidaMPop = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        CampoTextPaisParaEditarCidMPop = new javax.swing.JTextField();
        BotaoEditaCidadeMPop = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CampoTextCidadeMPop = new javax.swing.JTextField();
        JanelaProcPaisContinente = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        CampoTextContinente = new javax.swing.JTextField();
        BotaoPesquisaPaisContinente = new javax.swing.JButton();
        JanelaProcPaisLingua = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        CampoTextLingua = new javax.swing.JTextField();
        BotaoPesquisaPaisLingua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        MenuBar = new javax.swing.JMenuBar();
        MenuPrincipal = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();
        MenuXML = new javax.swing.JMenu();
        VerPaisesXML = new javax.swing.JMenuItem();
        ApagarPaisesXML = new javax.swing.JMenuItem();
        VerFactosXML = new javax.swing.JMenuItem();
        ApagarFactosXML = new javax.swing.JMenuItem();
        MenuAdicionar = new javax.swing.JMenu();
        AdicionarPais = new javax.swing.JMenuItem();
        MenuEditar = new javax.swing.JMenu();
        EditarPresPais = new javax.swing.JMenuItem();
        EditarPopPais = new javax.swing.JMenuItem();
        EditarCidMPop = new javax.swing.JMenuItem();
        MenuRemover = new javax.swing.JMenu();
        RemoverPais = new javax.swing.JMenuItem();
        MenuXSLT = new javax.swing.JMenu();
        XMLparaHTML_FLAGS = new javax.swing.JMenuItem();
        XMLparaTXT_TOP5 = new javax.swing.JMenuItem();
        XMLparaXML_EURO = new javax.swing.JMenuItem();
        MenuXPATH = new javax.swing.JMenu();
        ProcurarPaisesPorContinente = new javax.swing.JMenuItem();
        ProcuraPaisesPorContinente = new javax.swing.JMenuItem();
        MenuValidar = new javax.swing.JMenu();
        ValidarPaisesDTD = new javax.swing.JMenuItem();
        ValidarFactosDTD = new javax.swing.JMenuItem();
        ValidarPaisesXSD = new javax.swing.JMenuItem();
        ValidarFactosXSD = new javax.swing.JMenuItem();

        jLabel1.setText("Nome do País:");

        BotaoAdicionarPais.setText("Adicionar");
        BotaoAdicionarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAdicionarPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JanelaAdicionaPaisLayout = new javax.swing.GroupLayout(JanelaAdicionaPais.getContentPane());
        JanelaAdicionaPais.getContentPane().setLayout(JanelaAdicionaPaisLayout);
        JanelaAdicionaPaisLayout.setHorizontalGroup(
            JanelaAdicionaPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JanelaAdicionaPaisLayout.createSequentialGroup()
                .addGroup(JanelaAdicionaPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JanelaAdicionaPaisLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(CampoTextPaisParaAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(JanelaAdicionaPaisLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoAdicionarPais)))
                .addGap(32, 32, 32))
        );
        JanelaAdicionaPaisLayout.setVerticalGroup(
            JanelaAdicionaPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JanelaAdicionaPaisLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(JanelaAdicionaPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CampoTextPaisParaAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoAdicionarPais)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jLabel2.setText("Nome do País:");

        BotaoRemoverPais.setText("Remover");
        BotaoRemoverPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRemoverPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JanelaRemovePaisLayout = new javax.swing.GroupLayout(JanelaRemovePais.getContentPane());
        JanelaRemovePais.getContentPane().setLayout(JanelaRemovePaisLayout);
        JanelaRemovePaisLayout.setHorizontalGroup(
            JanelaRemovePaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JanelaRemovePaisLayout.createSequentialGroup()
                .addGroup(JanelaRemovePaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JanelaRemovePaisLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoRemoverPais))
                    .addGroup(JanelaRemovePaisLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(CampoTextPaisParaRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                .addGap(31, 31, 31))
        );
        JanelaRemovePaisLayout.setVerticalGroup(
            JanelaRemovePaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JanelaRemovePaisLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(JanelaRemovePaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CampoTextPaisParaRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoRemoverPais)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jLabel3.setText("Nome do País:");

        BotaoEditaPresi.setText("Alterar Informação");
        BotaoEditaPresi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditaPresiActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome do Presidente:");

        CampoTextPresidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextPresidenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JanelaEditaPresiLayout = new javax.swing.GroupLayout(JanelaEditaPresi.getContentPane());
        JanelaEditaPresi.getContentPane().setLayout(JanelaEditaPresiLayout);
        JanelaEditaPresiLayout.setHorizontalGroup(
            JanelaEditaPresiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JanelaEditaPresiLayout.createSequentialGroup()
                .addGroup(JanelaEditaPresiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JanelaEditaPresiLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoEditaPresi))
                    .addGroup(JanelaEditaPresiLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(JanelaEditaPresiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(7, 7, 7)
                        .addGroup(JanelaEditaPresiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CampoTextPaisParaEditarPres)
                            .addComponent(CampoTextPresidente, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))))
                .addGap(31, 31, 31))
        );
        JanelaEditaPresiLayout.setVerticalGroup(
            JanelaEditaPresiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JanelaEditaPresiLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(JanelaEditaPresiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CampoTextPaisParaEditarPres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JanelaEditaPresiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CampoTextPresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotaoEditaPresi)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel5.setText("Nome do País:");

        BotaoEditaPop.setText("Alterar Informação");
        BotaoEditaPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditaPopActionPerformed(evt);
            }
        });

        jLabel6.setText("População:");

        CampoTextPopulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextPopulacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JanelaEditaPopLayout = new javax.swing.GroupLayout(JanelaEditaPop.getContentPane());
        JanelaEditaPop.getContentPane().setLayout(JanelaEditaPopLayout);
        JanelaEditaPopLayout.setHorizontalGroup(
            JanelaEditaPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JanelaEditaPopLayout.createSequentialGroup()
                .addGroup(JanelaEditaPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JanelaEditaPopLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoEditaPop))
                    .addGroup(JanelaEditaPopLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(JanelaEditaPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(7, 7, 7)
                        .addGroup(JanelaEditaPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CampoTextPaisParaEditarPop)
                            .addComponent(CampoTextPopulacao, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))))
                .addGap(31, 31, 31))
        );
        JanelaEditaPopLayout.setVerticalGroup(
            JanelaEditaPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JanelaEditaPopLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(JanelaEditaPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CampoTextPaisParaEditarPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JanelaEditaPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CampoTextPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotaoEditaPop)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel7.setText("Nome do País:");

        BotaoEditaCidadeMPop.setText("Alterar Informação");
        BotaoEditaCidadeMPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditaCidadeMPopActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome da Cidade");

        CampoTextCidadeMPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextCidadeMPopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JanelaEditaCidaMPopLayout = new javax.swing.GroupLayout(JanelaEditaCidaMPop.getContentPane());
        JanelaEditaCidaMPop.getContentPane().setLayout(JanelaEditaCidaMPopLayout);
        JanelaEditaCidaMPopLayout.setHorizontalGroup(
            JanelaEditaCidaMPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JanelaEditaCidaMPopLayout.createSequentialGroup()
                .addGroup(JanelaEditaCidaMPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JanelaEditaCidaMPopLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoEditaCidadeMPop))
                    .addGroup(JanelaEditaCidaMPopLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(JanelaEditaCidaMPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(7, 7, 7)
                        .addGroup(JanelaEditaCidaMPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CampoTextPaisParaEditarCidMPop)
                            .addComponent(CampoTextCidadeMPop, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))))
                .addGap(31, 31, 31))
        );
        JanelaEditaCidaMPopLayout.setVerticalGroup(
            JanelaEditaCidaMPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JanelaEditaCidaMPopLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(JanelaEditaCidaMPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CampoTextPaisParaEditarCidMPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JanelaEditaCidaMPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CampoTextCidadeMPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotaoEditaCidadeMPop)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel9.setText("Nome do Continente:");

        CampoTextContinente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextContinenteActionPerformed(evt);
            }
        });

        BotaoPesquisaPaisContinente.setText("Pesquisar");
        BotaoPesquisaPaisContinente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPesquisaPaisContinenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JanelaProcPaisContinenteLayout = new javax.swing.GroupLayout(JanelaProcPaisContinente.getContentPane());
        JanelaProcPaisContinente.getContentPane().setLayout(JanelaProcPaisContinenteLayout);
        JanelaProcPaisContinenteLayout.setHorizontalGroup(
            JanelaProcPaisContinenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JanelaProcPaisContinenteLayout.createSequentialGroup()
                .addGroup(JanelaProcPaisContinenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JanelaProcPaisContinenteLayout.createSequentialGroup()
                        .addContainerGap(269, Short.MAX_VALUE)
                        .addComponent(BotaoPesquisaPaisContinente))
                    .addGroup(JanelaProcPaisContinenteLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel9)
                        .addGap(17, 17, 17)
                        .addComponent(CampoTextContinente)))
                .addGap(31, 31, 31))
        );
        JanelaProcPaisContinenteLayout.setVerticalGroup(
            JanelaProcPaisContinenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JanelaProcPaisContinenteLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(JanelaProcPaisContinenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CampoTextContinente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotaoPesquisaPaisContinente)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel10.setText("Língua Oficial:");

        CampoTextLingua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextLinguaActionPerformed(evt);
            }
        });

        BotaoPesquisaPaisLingua.setText("Pesquisar");
        BotaoPesquisaPaisLingua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPesquisaPaisLinguaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JanelaProcPaisLinguaLayout = new javax.swing.GroupLayout(JanelaProcPaisLingua.getContentPane());
        JanelaProcPaisLingua.getContentPane().setLayout(JanelaProcPaisLinguaLayout);
        JanelaProcPaisLinguaLayout.setHorizontalGroup(
            JanelaProcPaisLinguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JanelaProcPaisLinguaLayout.createSequentialGroup()
                .addGroup(JanelaProcPaisLinguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JanelaProcPaisLinguaLayout.createSequentialGroup()
                        .addContainerGap(269, Short.MAX_VALUE)
                        .addComponent(BotaoPesquisaPaisLingua))
                    .addGroup(JanelaProcPaisLinguaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel10)
                        .addGap(17, 17, 17)
                        .addComponent(CampoTextLingua)))
                .addGap(31, 31, 31))
        );
        JanelaProcPaisLinguaLayout.setVerticalGroup(
            JanelaProcPaisLinguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JanelaProcPaisLinguaLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(JanelaProcPaisLinguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CampoTextLingua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotaoPesquisaPaisLingua)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        MenuPrincipal.setText("Principal");

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        MenuPrincipal.add(Sair);

        MenuBar.add(MenuPrincipal);

        MenuXML.setText("XML");

        VerPaisesXML.setText("Ver ficheiro paises.xml");
        VerPaisesXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerPaisesXMLActionPerformed(evt);
            }
        });
        MenuXML.add(VerPaisesXML);

        ApagarPaisesXML.setText("Apagar ficheiro paises.xml");
        ApagarPaisesXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarPaisesXMLActionPerformed(evt);
            }
        });
        MenuXML.add(ApagarPaisesXML);

        VerFactosXML.setText("Ver ficheiro factos.xml");
        VerFactosXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerFactosXMLActionPerformed(evt);
            }
        });
        MenuXML.add(VerFactosXML);

        ApagarFactosXML.setText("Apagar ficheiro factos.xml");
        ApagarFactosXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarFactosXMLActionPerformed(evt);
            }
        });
        MenuXML.add(ApagarFactosXML);

        MenuBar.add(MenuXML);

        MenuAdicionar.setText("Adicionar");

        AdicionarPais.setText("Adicionar info de um País");
        AdicionarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarPaisActionPerformed(evt);
            }
        });
        MenuAdicionar.add(AdicionarPais);

        MenuBar.add(MenuAdicionar);

        MenuEditar.setText("Editar");

        EditarPresPais.setText("Editar Presidente de um País");
        EditarPresPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPresPaisActionPerformed(evt);
            }
        });
        MenuEditar.add(EditarPresPais);

        EditarPopPais.setText("Editar População de um País");
        EditarPopPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPopPaisActionPerformed(evt);
            }
        });
        MenuEditar.add(EditarPopPais);

        EditarCidMPop.setText("Editar Cidade Mais Populosa de um País");
        EditarCidMPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarCidMPopActionPerformed(evt);
            }
        });
        MenuEditar.add(EditarCidMPop);

        MenuBar.add(MenuEditar);

        MenuRemover.setText("Remover");

        RemoverPais.setText("Remover info de um País");
        RemoverPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverPaisActionPerformed(evt);
            }
        });
        MenuRemover.add(RemoverPais);

        MenuBar.add(MenuRemover);

        MenuXSLT.setText("XSLT");

        XMLparaHTML_FLAGS.setText("XML para HTML --> Bandeiras");
        XMLparaHTML_FLAGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XMLparaHTML_FLAGSActionPerformed(evt);
            }
        });
        MenuXSLT.add(XMLparaHTML_FLAGS);

        XMLparaTXT_TOP5.setText("XML para TXT --> Top 5 Pop");
        XMLparaTXT_TOP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XMLparaTXT_TOP5ActionPerformed(evt);
            }
        });
        MenuXSLT.add(XMLparaTXT_TOP5);

        XMLparaXML_EURO.setText("XML para XML --> Euro");
        XMLparaXML_EURO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XMLparaXML_EUROActionPerformed(evt);
            }
        });
        MenuXSLT.add(XMLparaXML_EURO);

        MenuBar.add(MenuXSLT);

        MenuXPATH.setText("Xpath");

        ProcurarPaisesPorContinente.setText("Procurar Países por Continente");
        ProcurarPaisesPorContinente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcurarPaisesPorContinenteActionPerformed(evt);
            }
        });
        MenuXPATH.add(ProcurarPaisesPorContinente);

        ProcuraPaisesPorContinente.setText("Procurar Países por Língua");
        ProcuraPaisesPorContinente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcuraPaisesPorContinenteActionPerformed(evt);
            }
        });
        MenuXPATH.add(ProcuraPaisesPorContinente);

        MenuBar.add(MenuXPATH);

        MenuValidar.setText("Validar");

        ValidarPaisesDTD.setText("Validar paises.xml DTD");
        ValidarPaisesDTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidarPaisesDTDActionPerformed(evt);
            }
        });
        MenuValidar.add(ValidarPaisesDTD);

        ValidarFactosDTD.setText("Validar factos.xml DTD");
        ValidarFactosDTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidarFactosDTDActionPerformed(evt);
            }
        });
        MenuValidar.add(ValidarFactosDTD);

        ValidarPaisesXSD.setText("Validar paises.xml XSD");
        ValidarPaisesXSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidarPaisesXSDActionPerformed(evt);
            }
        });
        MenuValidar.add(ValidarPaisesXSD);

        ValidarFactosXSD.setText("Validar factos.xml XSD");
        ValidarFactosXSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidarFactosXSDActionPerformed(evt);
            }
        });
        MenuValidar.add(ValidarFactosXSD);

        MenuBar.add(MenuValidar);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void VerPaisesXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPaisesXMLActionPerformed
        // TODO add your handling code here:
        Document doc = XMLJDomFunctions.lerDocumentoXML("paises.xml");
        String s = "Ficheiro Não Existe";
        if (doc != null) {
            s = XMLJDomFunctions.escreverDocumentoString(doc);
        }
        jTextArea1.setText(s);
    }//GEN-LAST:event_VerPaisesXMLActionPerformed

    private void VerFactosXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerFactosXMLActionPerformed
        // TODO add your handling code here:
        Document doc = XMLJDomFunctions.lerDocumentoXML("factos.xml");
        String s = "Ficheiro Não Existe";
        if (doc != null) {
            s = XMLJDomFunctions.escreverDocumentoString(doc);
        }
        jTextArea1.setText(s);
    }//GEN-LAST:event_VerFactosXMLActionPerformed

    private void ApagarPaisesXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarPaisesXMLActionPerformed
        // TODO add your handling code here:
        File f = new File("paises.xml");
        if (f != null) {
            f.delete();
        }
        jTextArea1.setText("Ficheiro Removido");
    }//GEN-LAST:event_ApagarPaisesXMLActionPerformed

    private void ApagarFactosXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarFactosXMLActionPerformed
        // TODO add your handling code here:
        File f = new File("factos.xml");
        if (f != null) {
            f.delete();
        }
        jTextArea1.setText("Ficheiro Removido");
    }//GEN-LAST:event_ApagarFactosXMLActionPerformed

    private void AdicionarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarPaisActionPerformed
        JanelaAdicionaPais.setSize(400, 200);
        JanelaAdicionaPais.setLocation(300, 300);
        JanelaAdicionaPais.setTitle("Adicionar um País");
        JanelaAdicionaPais.setVisible(true);
    }//GEN-LAST:event_AdicionarPaisActionPerformed

    
    private void BotaoAdicionarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAdicionarPaisActionPerformed
        // TODO add your handling code here:
        String pesquisa = CampoTextPaisParaAdicionar.getText();
        
        try {
            adicionaInfoAmbosFicheiros(pesquisa);
        } catch (IOException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SaxonApiException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoAdicionarPaisActionPerformed

    private void BotaoRemoverPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRemoverPaisActionPerformed
        // TODO add your handling code here:
        String pesquisa = CampoTextPaisParaRemover.getText();
        
        removePaisFicheiros(pesquisa);
    }//GEN-LAST:event_BotaoRemoverPaisActionPerformed

    private void RemoverPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverPaisActionPerformed
        JanelaRemovePais.setSize(400, 200);
        JanelaRemovePais.setLocation(300, 300);
        JanelaRemovePais.setTitle("Remover um País");
        JanelaRemovePais.setVisible(true);
    }//GEN-LAST:event_RemoverPaisActionPerformed

    private void BotaoEditaPresiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditaPresiActionPerformed
        // TODO add your handling code here:
        String pesquisa = CampoTextPaisParaEditarPres.getText();
        String novo_pres = CampoTextPresidente.getText();
        
        alteraPresidente(pesquisa, novo_pres);
    }//GEN-LAST:event_BotaoEditaPresiActionPerformed

    private void CampoTextPresidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextPresidenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTextPresidenteActionPerformed

    private void EditarPresPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPresPaisActionPerformed
        // TODO add your handling code here:
        JanelaEditaPresi.setSize(400, 250);
        JanelaEditaPresi.setLocation(300, 300);
        JanelaEditaPresi.setTitle("Editar Presidente de um país");
        JanelaEditaPresi.setVisible(true);
    }//GEN-LAST:event_EditarPresPaisActionPerformed

    private void BotaoEditaPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditaPopActionPerformed
        // TODO add your handling code here:
        String pesquisa = CampoTextPaisParaEditarPop.getText();
        String pop = CampoTextPopulacao.getText();
        
        alteraPopulacao(pesquisa, pop);
    }//GEN-LAST:event_BotaoEditaPopActionPerformed

    private void CampoTextPopulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextPopulacaoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CampoTextPopulacaoActionPerformed

    private void EditarPopPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPopPaisActionPerformed
        // TODO add your handling code here:
        JanelaEditaPop.setSize(400, 250);
        JanelaEditaPop.setLocation(300, 300);
        JanelaEditaPop.setTitle("Editar População de um país");
        JanelaEditaPop.setVisible(true);
    }//GEN-LAST:event_EditarPopPaisActionPerformed

    private void EditarCidMPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarCidMPopActionPerformed
        // TODO add your handling code here:
        JanelaEditaCidaMPop.setSize(400, 250);
        JanelaEditaCidaMPop.setLocation(300, 300);
        JanelaEditaCidaMPop.setTitle("Editar Cidade mais populosa de um país");
        JanelaEditaCidaMPop.setVisible(true);
    }//GEN-LAST:event_EditarCidMPopActionPerformed

    private void XMLparaHTML_FLAGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XMLparaHTML_FLAGSActionPerformed
        // TODO add your handling code here:
        Document doc = XMLJDomFunctions.lerDocumentoXML("paises.xml");
        if (doc != null) {
            Document novo = JDOMFunctions_XSLT.transformaDocumento(doc, "paises.xml", "transf_html.xsl");
            XMLJDomFunctions.escreverDocumentoParaFicheiro(novo, "teste.html");
            doc = XMLJDomFunctions.lerDocumentoXML("teste.html");
            String t = XMLJDomFunctions.escreverDocumentoString(doc);
            String url = "teste.html";
            File htmlFile = new File(url);
            try {
                Desktop.getDesktop().browse(htmlFile.toURI());
            } catch (IOException ex) {
                Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_XMLparaHTML_FLAGSActionPerformed

    private void ValidarPaisesDTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidarPaisesDTDActionPerformed
        try {
            // TODO add your handling code here:
            String s;
            s=validarDocumentoDTD("paises.xml", "paises.dtd");
            jTextArea1.setText(s);
        } catch (IOException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ValidarPaisesDTDActionPerformed

    private void ValidarFactosDTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidarFactosDTDActionPerformed
        try {
            // TODO add your handling code here:
            String s;
            s=validarDocumentoDTD("factos.xml", "factos.dtd");
            jTextArea1.setText(s);
        } catch (IOException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ValidarFactosDTDActionPerformed

    private void ValidarPaisesXSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidarPaisesXSDActionPerformed
        // TODO add your handling code here:
        String s;
        s=validarDocumentoXSD("paises.xml", "paises.xsd");
        jTextArea1.setText(s);
    }//GEN-LAST:event_ValidarPaisesXSDActionPerformed

    private void ValidarFactosXSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidarFactosXSDActionPerformed
        // TODO add your handling code here:
        String s;
        s=validarDocumentoXSD("factos.xml", "factos.xsd");
        jTextArea1.setText(s);
    }//GEN-LAST:event_ValidarFactosXSDActionPerformed

    private void XMLparaTXT_TOP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XMLparaTXT_TOP5ActionPerformed
        // TODO add your handling code here:
        Document doc = XMLJDomFunctions.lerDocumentoXML("factos.xml");
        if (doc != null) {
            Document novo = JDOMFunctions_XSLT.transformaDocumento(doc, "factos.xml", "transf_txt.xsl");
            XMLJDomFunctions.escreverDocumentoParaFicheiro(novo, "TOP_5_POP.txt");
            doc = XMLJDomFunctions.lerDocumentoXML("TOP_5_POP.txt");
            String t = XMLJDomFunctions.escreverDocumentoString(doc);
            String url = "TOP_5_POP.txt";
            File txtFile = new File(url);
            try {
                Desktop.getDesktop().browse(txtFile.toURI());
            } catch (IOException ex) {
                Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_XMLparaTXT_TOP5ActionPerformed

    private void BotaoEditaCidadeMPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditaCidadeMPopActionPerformed
        // TODO add your handling code here:
        String procura = CampoTextPaisParaEditarCidMPop.getText();
        String novaCidMP = CampoTextCidadeMPop.getText();
        
        alteraCidadePopulosa(procura, novaCidMP);
    }//GEN-LAST:event_BotaoEditaCidadeMPopActionPerformed

    private void CampoTextCidadeMPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextCidadeMPopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTextCidadeMPopActionPerformed

    private void ProcurarPaisesPorContinenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcurarPaisesPorContinenteActionPerformed
        // TODO add your handling code here:
        JanelaProcPaisContinente.setSize(400, 250);
        JanelaProcPaisContinente.setLocation(300, 300);
        JanelaProcPaisContinente.setTitle("Procurar Países por Continente");
        JanelaProcPaisContinente.setVisible(true);        
    }//GEN-LAST:event_ProcurarPaisesPorContinenteActionPerformed

    private void BotaoPesquisaPaisContinenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPesquisaPaisContinenteActionPerformed
        // TODO add your handling code here:
        String procura = CampoTextContinente.getText();
        String s;
        try {
            s = procura_pais_por_continente(procura);
            jTextArea1.setText(s);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SaxonApiException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoPesquisaPaisContinenteActionPerformed

    private void CampoTextContinenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextContinenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTextContinenteActionPerformed

    private void XMLparaXML_EUROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XMLparaXML_EUROActionPerformed
        // TODO add your handling code here:
        Document doc = XMLJDomFunctions.lerDocumentoXML("factos.xml");
        if (doc != null) {
            Document novo = JDOMFunctions_XSLT.transformaDocumento(doc, "factos.xml", "transf_xml_EURO.xsl");
            XMLJDomFunctions.escreverDocumentoParaFicheiro(novo, "EURO.xml");
            doc = XMLJDomFunctions.lerDocumentoXML("EURO.xml");
            String t = XMLJDomFunctions.escreverDocumentoString(doc);
            jTextArea1.setText(t);
         }
    }//GEN-LAST:event_XMLparaXML_EUROActionPerformed

    private void CampoTextLinguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextLinguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTextLinguaActionPerformed

    private void BotaoPesquisaPaisLinguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPesquisaPaisLinguaActionPerformed
        // TODO add your handling code here:
        String procura = CampoTextLingua.getText();
        String s;
        try {
            s = procura_pais_por_idioma(procura);
            jTextArea1.setText(s);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SaxonApiException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BotaoPesquisaPaisLinguaActionPerformed

    private void ProcuraPaisesPorContinenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcuraPaisesPorContinenteActionPerformed
        // TODO add your handling code here:
        JanelaProcPaisLingua.setSize(400, 250);
        JanelaProcPaisLingua.setLocation(300, 300);
        JanelaProcPaisLingua.setTitle("Procurar Países por Língua Oficial");
        JanelaProcPaisLingua.setVisible(true);
    }//GEN-LAST:event_ProcuraPaisesPorContinenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AdicionarPais;
    private javax.swing.JMenuItem ApagarFactosXML;
    private javax.swing.JMenuItem ApagarPaisesXML;
    private javax.swing.JButton BotaoAdicionarPais;
    private javax.swing.JButton BotaoEditaCidadeMPop;
    private javax.swing.JButton BotaoEditaPop;
    private javax.swing.JButton BotaoEditaPresi;
    private javax.swing.JButton BotaoPesquisaPaisContinente;
    private javax.swing.JButton BotaoPesquisaPaisLingua;
    private javax.swing.JButton BotaoRemoverPais;
    private javax.swing.JTextField CampoTextCidadeMPop;
    private javax.swing.JTextField CampoTextContinente;
    private javax.swing.JTextField CampoTextLingua;
    private javax.swing.JTextField CampoTextPaisParaAdicionar;
    private javax.swing.JTextField CampoTextPaisParaEditarCidMPop;
    private javax.swing.JTextField CampoTextPaisParaEditarPop;
    private javax.swing.JTextField CampoTextPaisParaEditarPres;
    private javax.swing.JTextField CampoTextPaisParaRemover;
    private javax.swing.JTextField CampoTextPopulacao;
    private javax.swing.JTextField CampoTextPresidente;
    private javax.swing.JMenuItem EditarCidMPop;
    private javax.swing.JMenuItem EditarPopPais;
    private javax.swing.JMenuItem EditarPresPais;
    private javax.swing.JDialog JanelaAdicionaPais;
    private javax.swing.JDialog JanelaEditaCidaMPop;
    private javax.swing.JDialog JanelaEditaPop;
    private javax.swing.JDialog JanelaEditaPresi;
    private javax.swing.JDialog JanelaProcPaisContinente;
    private javax.swing.JDialog JanelaProcPaisLingua;
    private javax.swing.JDialog JanelaRemovePais;
    private javax.swing.JMenu MenuAdicionar;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuEditar;
    private javax.swing.JMenu MenuPrincipal;
    private javax.swing.JMenu MenuRemover;
    private javax.swing.JMenu MenuValidar;
    private javax.swing.JMenu MenuXML;
    private javax.swing.JMenu MenuXPATH;
    private javax.swing.JMenu MenuXSLT;
    private javax.swing.JMenuItem ProcuraPaisesPorContinente;
    private javax.swing.JMenuItem ProcurarPaisesPorContinente;
    private javax.swing.JMenuItem RemoverPais;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenuItem ValidarFactosDTD;
    private javax.swing.JMenuItem ValidarFactosXSD;
    private javax.swing.JMenuItem ValidarPaisesDTD;
    private javax.swing.JMenuItem ValidarPaisesXSD;
    private javax.swing.JMenuItem VerFactosXML;
    private javax.swing.JMenuItem VerPaisesXML;
    private javax.swing.JMenuItem XMLparaHTML_FLAGS;
    private javax.swing.JMenuItem XMLparaTXT_TOP5;
    private javax.swing.JMenuItem XMLparaXML_EURO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private String procura_pais_por_lingua(String procura) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
