/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp_id;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.saxon.s9api.SaxonApiException;
import org.jdom2.Document;
import static tp_id.TP_ID.adicionaInfoAmbosFicheiros;

/**
 *
 * @author joaop
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        CampoTextPaisParaAdicionar = new javax.swing.JTextField();
        BotaoAdicionarPais = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        MenuBar = new javax.swing.JMenuBar();
        MenuPrincipal = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();
        MenuXML = new javax.swing.JMenu();
        VerPaisesXML = new javax.swing.JMenuItem();
        ApagarPaisesXML = new javax.swing.JMenuItem();
        VerFactosXML = new javax.swing.JMenuItem();
        ApagarFactosXML = new javax.swing.JMenuItem();
        MenuAdicionar = new javax.swing.JMenu();
        AdicionarPais = new javax.swing.JMenuItem();

        jLabel1.setText("Nome do País:");

        BotaoAdicionarPais.setText("Adicionar");
        BotaoAdicionarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAdicionarPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58)
                        .addComponent(CampoTextPaisParaAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoAdicionarPais)))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CampoTextPaisParaAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoAdicionarPais)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        MenuPrincipal.setText("Principal");

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        MenuPrincipal.add(Sair);

        MenuBar.add(MenuPrincipal);

        MenuXML.setText("XML");

        VerPaisesXML.setText("Ver ficheiro paises.xml");
        VerPaisesXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerPaisesXMLActionPerformed(evt);
            }
        });
        MenuXML.add(VerPaisesXML);

        ApagarPaisesXML.setText("Apagar ficheiro paises.xml");
        ApagarPaisesXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarPaisesXMLActionPerformed(evt);
            }
        });
        MenuXML.add(ApagarPaisesXML);

        VerFactosXML.setText("Ver ficheiro factos.xml");
        VerFactosXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerFactosXMLActionPerformed(evt);
            }
        });
        MenuXML.add(VerFactosXML);

        ApagarFactosXML.setText("Apagar ficheiro factos.xml");
        ApagarFactosXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarFactosXMLActionPerformed(evt);
            }
        });
        MenuXML.add(ApagarFactosXML);

        MenuBar.add(MenuXML);

        MenuAdicionar.setText("Adicionar");

        AdicionarPais.setText("Adicionar info de um país");
        AdicionarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarPaisActionPerformed(evt);
            }
        });
        MenuAdicionar.add(AdicionarPais);

        MenuBar.add(MenuAdicionar);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void VerPaisesXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPaisesXMLActionPerformed
        // TODO add your handling code here:
        Document doc = XMLJDomFunctions.lerDocumentoXML("paises.xml");
        String s = "Ficheiro Não Existe";
        if (doc != null) {
            s = XMLJDomFunctions.escreverDocumentoString(doc);
        }
        jTextArea1.setText(s);
    }//GEN-LAST:event_VerPaisesXMLActionPerformed

    private void VerFactosXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerFactosXMLActionPerformed
        // TODO add your handling code here:
        Document doc = XMLJDomFunctions.lerDocumentoXML("factos.xml");
        String s = "Ficheiro Não Existe";
        if (doc != null) {
            s = XMLJDomFunctions.escreverDocumentoString(doc);
        }
        jTextArea1.setText(s);
    }//GEN-LAST:event_VerFactosXMLActionPerformed

    private void ApagarPaisesXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarPaisesXMLActionPerformed
        // TODO add your handling code here:
        File f = new File("paises.xml");
        if (f != null) {
            f.delete();
        }
        jTextArea1.setText("Ficheiro Removido");
    }//GEN-LAST:event_ApagarPaisesXMLActionPerformed

    private void ApagarFactosXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarFactosXMLActionPerformed
        // TODO add your handling code here:
        File f = new File("factos.xml");
        if (f != null) {
            f.delete();
        }
        jTextArea1.setText("Ficheiro Removido");
    }//GEN-LAST:event_ApagarFactosXMLActionPerformed

    private void AdicionarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarPaisActionPerformed
        jDialog1.setSize(400, 200);
        jDialog1.setLocation(300, 300);
        jDialog1.setTitle("Pesquisar por Autor");
        jDialog1.setVisible(true);
    }//GEN-LAST:event_AdicionarPaisActionPerformed

    private void BotaoAdicionarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAdicionarPaisActionPerformed
        // TODO add your handling code here:
        String pesquisa = CampoTextPaisParaAdicionar.getText();
        
        try {
            adicionaInfoAmbosFicheiros(pesquisa);
        } catch (IOException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SaxonApiException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoAdicionarPaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AdicionarPais;
    private javax.swing.JMenuItem ApagarFactosXML;
    private javax.swing.JMenuItem ApagarPaisesXML;
    private javax.swing.JButton BotaoAdicionarPais;
    private javax.swing.JTextField CampoTextPaisParaAdicionar;
    private javax.swing.JMenu MenuAdicionar;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuPrincipal;
    private javax.swing.JMenu MenuXML;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenuItem VerFactosXML;
    private javax.swing.JMenuItem VerPaisesXML;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
